In [1]:
import numpy as np

t = np.array([0., 1., 2., 3., 4., 5., 6.])
t

array([0., 1., 2., 3., 4., 5., 6.])

In [2]:
t.ndim, t.shape

(1, (7,))

In [3]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [4]:
t.ndim, t.shape

(2, (4, 3))

In [5]:
# torch
import torch

In [6]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [7]:
t.dim(), t.shape, t.size()

(1, torch.Size([7]), torch.Size([7]))

In [8]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [9]:
t.dim(), t.shape

(2, torch.Size([4, 3]))

In [11]:
t[:,1], t[:,1].size()

(tensor([ 2.,  5.,  8., 11.]), torch.Size([4]))

In [12]:
print(t[:, :-1])

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [13]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
m1+m2

tensor([[5., 5.]])

In [14]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3])
m1+m2

tensor([[4., 5.]])

In [15]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


In [16]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [17]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [18]:
t = torch.FloatTensor([1,2])
t.mean()

tensor(1.5000)

In [19]:
t = torch.FloatTensor([[1, 2], [3, 4]])
t.mean()

tensor(2.5000)

In [20]:
t.mean(dim=0)

tensor([2., 3.])

In [21]:
t.mean(dim=1)

tensor([1.5000, 3.5000])

In [22]:
t.mean(dim=-1)

tensor([1.5000, 3.5000])

In [23]:
print(t.sum()) # 단순히 원소 전체의 덧셈을 수행
print(t.sum(dim=0)) # 행을 제거
print(t.sum(dim=1)) # 열을 제거
print(t.sum(dim=-1)) # 열을 제거

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [24]:
t.max()

tensor(4.)

In [25]:
t.max(dim=0)

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))

In [26]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


In [27]:
# view
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

ft.shape

torch.Size([2, 2, 3])

In [29]:
ft.view([-1,3]), ft.view([-1,3]).size()

(tensor([[ 0.,  1.,  2.],
         [ 3.,  4.,  5.],
         [ 6.,  7.,  8.],
         [ 9., 10., 11.]]),
 torch.Size([4, 3]))

In [30]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [31]:
# squeeze
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)


tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [32]:
ft.squeeze(), ft.squeeze().size()

(tensor([0., 1., 2.]), torch.Size([3]))

In [3]:
ft = torch.Tensor([0,1,2])
ft.size()

torch.Size([3])

In [4]:
ft.unsqueeze(0), ft.unsqueeze(0).size()

(tensor([[0., 1., 2.]]), torch.Size([1, 3]))

In [5]:
ft.view([-1,1]), ft.view([-1,1]).size()

(tensor([[0.],
         [1.],
         [2.]]),
 torch.Size([3, 1]))

In [6]:
ft.unsqueeze(1), ft.unsqueeze(1).size()

(tensor([[0.],
         [1.],
         [2.]]),
 torch.Size([3, 1]))

In [8]:
# type casting
lt = torch.LongTensor([1,2,3,4])
lt, lt.float()

(tensor([1, 2, 3, 4]), tensor([1., 2., 3., 4.]))

In [9]:
bt = torch.ByteTensor([True, False, False, True])
bt

tensor([1, 0, 0, 1], dtype=torch.uint8)

In [10]:
bt.long(), bt.float()

(tensor([1, 0, 0, 1]), tensor([1., 0., 0., 1.]))

In [11]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])
torch.concat([x,y], dim=0)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [12]:
torch.concat([x,y], dim=1)

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])

In [13]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

torch.stack([x,y,z])

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [14]:
torch.stack([x,y,z], dim=1)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [15]:
# ones_like, zeros_like
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
torch.ones_like(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [16]:
torch.zeros_like(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [17]:
x = torch.FloatTensor([[1, 2], [3, 4]])
x.mul(2.)

tensor([[2., 4.],
        [6., 8.]])

In [18]:
# in place operation
x.mul_(2.)
x

tensor([[2., 4.],
        [6., 8.]])